# Generated by Django 3.1.3 on 2021-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froggerFX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='highscore',
            field=models.BigIntegerField(default=0),
        ),
    ]
